name: deploy

on:
  push:
    tags:
      - "src/v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NODE_VERSION: "24"
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - run: pnpm i

      - run: pnpm run build

      - run: |
          mkdir dist/dist
          mv dist/index.js dist/dist/index.js
          cp action.yml dist

      - run: echo "TAG=v$(cat package.json | jq .version -r)" >> $GITHUB_ENV

      - name: Generate Changelog
        id: changelog
        uses: requarks/changelog-action@b78a3354a01f4a1affb484b9264b506a815c46b1 # v1.10.3
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          restrictToTypes: feat,fix,revert

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          commit_message: deploy ${{ github.ref }}
          publish_branch: dist/v0
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          tag_name: ${{ env.TAG }}
          tag_message: "release ${{ github.ref_name }}"

      - run: gh release create "${TAG}" --notes "${CHANGELOG}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: "${{ steps.changelog.outputs.changes }}"
